---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: 包含多項新功能與增強功能的資訊。Cloud Volumes ONTAP 
---
= 更新功能Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
包含多項新功能與增強功能的資訊。Cloud Volumes ONTAP

最新版的BlueXP也會提供其他功能和增強功能。請參閱 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["BlueXP版本說明"^] 以取得詳細資料。



== 不再支援的c4、m4和r4執行個體（2022年10月28日）

在AWS中Cloud Volumes ONTAP 、不再支援C4、M4和R4 EC2執行個體類型。如果現有系統執行的是c4、m4或r4執行個體類型、則必須變更為c5、m5或R5執行個體系列中的執行個體類型。

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html["瞭解如何變更EC2執行個體類型Cloud Volumes ONTAP 以供使用"^]。

請參閱 link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp支援"^] 以深入瞭解這些執行個體類型的終止可用度和支援。



== 最新更新（2021年4月21日）

在AWS中、您現在可以設定多達24個儲存VM（SVM）進行災難恢復（DR）。先前的限制是用於DR的12個儲存VM。

link:reference-limits-aws.html#storage-vm-limits["深入瞭解儲存VM限制"]。



== 最新更新（2021年4月12日）

自從發佈了更新版的更新版本、至今已有幾項Cloud Volumes ONTAP 更新。

* AWS更新*

* 從9.7版開始、支援通用SSD（GP3）磁碟。Cloud Volumes ONTAPGP3磁碟是成本最低的SSD、可在各種工作負載的成本與效能之間取得平衡。
+
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-planning-your-config.html#sizing-your-system-in-aws["深入瞭解搭配Cloud Volumes ONTAP 使用GP3磁碟的相關資訊"^]。

* 不再支援冷硬碟（SC1）磁碟。Cloud Volumes ONTAP


這些EBS磁碟變更是在BlueXP 3.9.5中引進的。

* Azure更新*

* 支援新的E系列VM類型：
+
** E4s_v3搭配使用PAYGO Explore或BYOL的單一節點系統
** E8s_v3搭配使用PAYGO Standard或BYOL的單一節點系統、以及使用PAYGO Premium或BYOL的HA配對
** E64is_v3搭配使用PAYGO Premium或BYOL的單一節點系統


* 支援多達24個儲存VM（SVM）Cloud Volumes ONTAP 、可搭配使用這24個儲存VM可以提供資料、或是設定災難恢復（DR）。
+
9.9.0版本先前的限制是Azure中用於災難恢復的12個儲存VM。





== 9.9.0 GA（2021年3月9日）

9.9.0 GA版本適用於AWS、Azure和Google Cloud Platform。此版本包含下列新功能與增強功能。



=== 提升寫入效能

此版本包含所有Cloud Volumes ONTAP 雲端供應商及所有組態中、針對VMware提供的更新寫入效能。



=== 支援新的EC2執行個體類型

下列Amazon EC2執行個體類型現在支援此功能：Cloud Volumes ONTAP

* M5a.2個大型、含標準及BYOL
* m5a.16xlarge搭配Premium和BYOL
* C5a.12xLarge搭配Premium和BYOL


深入瞭解 https://aws.amazon.com/ec2/instance-types/m5/["M5a執行個體"^] 和 https://aws.amazon.com/ec2/instance-types/c5/["C5A執行個體"^]。

link:reference-configs-aws.html["在AWS中檢視支援的組態"]。



=== 支援Azure中的24個儲存VM

當您攜帶自己的授權（BYOL）時、Azure現在支援Cloud Volumes ONTAP 24個儲存VM。這包括最多12個用於災難恢復的儲存VM。

在預設情況Cloud Volumes ONTAP 下、除了第一個隨附的儲存VM之外、每個額外的_data-Serving儲存VM都需要附加授權。請聯絡您的客戶團隊以取得 SVM 附加授權。

您設定用於災難恢復（DR）的儲存VM不需要附加授權（免費）、但它們確實會根據儲存VM的限制而計算。

link:reference-limits-azure.html#storage-vm-limits["深入瞭解Azure中的儲存VM限制"]。

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-azure.html["瞭解如何在Cloud Volumes ONTAP Azure中建立資料服務儲存VM以供其使用"^]。



== 所需版本的BlueXP Connector

BlueXP Connector必須執行3.9.4版或更新版本、才能部署新Cloud Volumes ONTAP 的版本號、並將現有系統升級至9.1.0版。



== 連接器3.9.4版所帶來的變更

連接器3.9.4版包含Cloud Volumes ONTAP 幾項加強功能、可用於管理各種版本的功能、包括增強AWS KMS支援、Google Cloud的共享VPC支援、以及Google Cloud的IP減少。

前往 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["BlueXP版本說明"^] 如需3.9.4版本的詳細資訊、



== 升級附註

* 必須從BlueXP完成升級。Cloud Volumes ONTAP您不應 Cloud Volumes ONTAP 使用 System Manager 或 CLI 來升級功能。這樣做可能會影響系統穩定性。
* 您可以從Cloud Volumes ONTAP 9.8版升級至版本的版本更新至版本更新。BlueXP會提示您將現有Cloud Volumes ONTAP 的更新版本升級至9.9.0。
+
http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["瞭解如何在BlueXP通知您時進行升級"^]。

* 單一節點系統的升級可讓系統離線長達25分鐘、在此期間I/O會中斷。
* 升級 HA 配對不中斷營運、而且 I/O 不中斷。在此不中斷營運的升級程序中、會同時升級每個節點、以繼續為用戶端提供 I/O 服務。

